#!/bin/bash
# scripts/setup_agents_md_sharing.sh
# 2026-05-24 | CR

set -e

write_long_reference_line() {
    local target_file="$1"
    echo "Use [CLAUDE.md](./CLAUDE.md) for the AI agent instructions. DO NOT EDIT THIS FILE." > ${target_file}
}

write_short_reference_line() {
    local target_file="$1"
    echo "@CLAUDE.md" > ${target_file}
}

set_symlink() {
    local source_file="$1"
    local target_file="$2"
    if [ -f "${source_file}" ] && [ ! -L "${target_file}" ]; then
        ln -sfn "${source_file}" "${target_file}"
    else
        echo "ERROR: Source file ${source_file} not found or target file ${target_file} is already a symlink"
        exit 1
    fi
}

main() {
    local action="$1"
    local operation_type="$2"
    local source_path="$3"
    local target_path="$4"
    local source_filename="CLAUDE.md"
    local target_filenames=("AGENTS.md" "GEMINI.md")

    cd "${source_path}"
    source_path="$(pwd)"
    cd - > /dev/null 2>&1

    cd "${target_path}"
    target_path="$(pwd)"
    cd - > /dev/null 2>&1

    for target_filename in "${target_filenames[@]}"; do
        if [ "$action" = "add" ]; then
            if [ "$operation_type" = "symlink" ]; then
                set_symlink "${source_path}/${source_filename}" "${target_path}/${target_filename}"
            elif [ "$operation_type" = "short" ]; then
                write_short_reference_line "${target_path}/${target_filename}"
            elif [ "$operation_type" = "long" ]; then
                write_long_reference_line "${target_path}/${target_filename}"
            else
                echo "ERROR: Invalid operation type: ${operation_type}"
                exit 1
            fi
        elif [ "$action" = "remove" ]; then
            rm -f "${target_path}/${target_filename}"
        else
            echo "ERROR: Invalid action: ${action}"
            exit 1
        fi
    done
}

show_usage() {
    echo ""
    echo "Usage: $0 <add|remove> <symlink|short|long> <source_path>"
    echo "  ACTION: add or remove"
    echo "  OPERATION_TYPE: symlink, short, long"
    echo "  SOURCE_PATH: path to the source file. Default is the current directory"
    echo "  TARGET_PATH: path to the target file. Default is the current directory."
    echo ""
    exit 1
}

ACTION="$1"
OPERATION_TYPE="$2"
SOURCE_PATH="$3"
TARGET_PATH="$4"

if [ "$ACTION" = "" ]; then
    echo "ERROR: ACTION is required"
    show_usage
fi
if [ "$OPERATION_TYPE" = "" ]; then
    echo "ERROR: OPERATION_TYPE is required"
    show_usage
fi
if [ "$SOURCE_PATH" = "" ]; then
    SOURCE_PATH="$PWD"
fi
if [ "$TARGET_PATH" = "" ]; then
    TARGET_PATH="$PWD"
fi

main "${ACTION}" "${OPERATION_TYPE}" "${SOURCE_PATH}" "${TARGET_PATH}"
